apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-ui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ops360
    name: in-cluster
  project: dev
  source:
    path: ops360/admin-ui
    repoURL: https://adebiyiadegboye@bitbucket.org/asset-control-acx/k8s-ops360-internal.git
    targetRevision: feature/kustomize
