apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-sets-perf
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ops360
    name: in-cluster
  project: perf
  source:
    path: uat-perf/perf/ops360/data-processing
    repoURL: git@bitbucket.org:asset-control-acx/ops360alpha-k8s-aws.git
    targetRevision: feature/argocd
